services:
  backend:
    build: ./backend
    container_name: legalaize-backend
    ports:
      - "8000:8000"
    volumes:
      #- ./backend:/app
      - ./params.yaml:/app/params.yaml:ro
      - ./data/mapping.json:/app/data/mapping.json:ro
      - ./data/processed/chunks.json:/app/data/processed/chunks.json:ro
      - ./data/processed/requirement_chunks.json:/app/data/processed/requirement_chunks.json:ro
    env_file:
      - .env
    environment:
      - PYTHONUNBUFFERED=1
      - PARAMS_PATH=/app/params.yaml
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    restart: unless-stopped


  frontend:
    build: ./frontend
    container_name: legalaize-frontend
    ports:
      - "8501:8501"
    depends_on:
      - backend
    environment:
      - PYTHONUNBUFFERED=1
      - BACKEND_URL=http://backend:8000
    volumes:
      - ./data/mapping.json:/data/mapping.json:ro
    restart: unless-stopped

networks:
  default:
    name: ml-network
