stages:
  ingest:
    cmd: python data_ingestion.py
    deps:
      - data_ingestion.py
      - data/ai_act.pdf
      - data/iso.pdf
      - params.yaml
    params:
      - ingestion
    outs:
      - data/processed/chunks.json

  vectorize:
    cmd: python vectorize_data.py
    deps:
      - vectorize_data.py
      - data/processed/chunks.json
      - params.yaml
    params:
      - vectorization
    outs:
      - data/processed/vector_index

  precompute_rag:
    cmd: python precompute_rag.py
    deps:
      - precompute_rag.py
      - data/mapping.json
      - params.yaml
      - data/processed/vector_index
    params:
      - vectorization
      - ingestion
    outs:
      - data/processed/requirement_chunks.json

  evaluate_rag:
    cmd: python evaluate_rag.py
    deps:
      - evaluate_rag.py
      - params.yaml
      - data/processed/requirement_chunks.json
      - data/ground_truth/raw_data/Evaluation1/documentation.txt
      - data/ground_truth/raw_data/Evaluation1/report.CSV
      - data/ground_truth/raw_data/Evaluation2/documentation.txt
      - data/ground_truth/raw_data/Evaluation2/report.CSV
    params:
      - evaluation
    outs:
      - metrics/rag_eval.json
