stages:
  ingest:
    cmd: python data_ingestion.py
    deps:
      - data_ingestion.py
      - data/ai_act.pdf
      - data/gdpr.pdf
      - params.yaml
    params:
      - ingestion
    outs:
      - data/processed/chunks.json

  vectorize:
    cmd: python vectorize_data.py
    deps:
      - vectorize_data.py
      - data/processed/chunks.json
      - params.yaml
    params:
      - vectorization
    outs:
      - data/processed/vector_index


  #train:
  #  cmd: python train_model.py
  #  deps:
  #    - train_model.py
  #    - params.yaml
  #    - data/
  #  params:
  #    - train
  #    - model
  #  outs:
  #    - models/model.pkl
  #  metrics:
  #    - metrics.json:
  #        cache: false
