stages:
  ingest:
    cmd: python data_ingestion.py
    deps:
      - data_ingestion.py
      - data/ai_act.pdf
      - data/gdpr.pdf
      - params.yaml
    params:
      - ingestion
    outs:
      - data/processed/chunks.json

  train:
    cmd: python train_model.py
    deps:
      - train_model.py
      - params.yaml
      - data/
    params:
      - train
      - model
    outs:
      - models/model.pkl
    metrics:
      - metrics.json:
          cache: false
