stages:
  ingest:
    cmd: 
      - python ingestion/data_ingestion.py
    deps:
      - ingestion/
      - data/raw_data/
    params:
      - ingestion
    outs:
      - data/processed/chunks.json

  vectorize:
    cmd: python vectorize_data.py
    deps:
      - vectorize_data.py
      - data/processed/chunks.json
    params:
      - vectorization
    outs:
      - data/processed/vector_index

  precompute_rag:
    cmd: python precompute_rag.py
    deps:
      - precompute_rag.py
      - data/mapping.json
      - data/processed/vector_index
    params:
      - vectorization
      - ingestion
    outs:
      - data/processed/requirement_chunks.json

  evaluate_rag:
    cmd: python evaluation/evaluate_rag.py
    deps:
      - evaluation/  
      - data/processed/requirement_chunks.json
      - data/ground_truth
    params:
      - evaluation
    outs:
      - metrics/rag_eval.json
