stages:
  ingest:
    cmd: python data_ingestion.py
    deps:
      - data_ingestion.py
      - data/ai_act.pdf
      - data/iso.pdf
      - params.yaml
    params:
      - ingestion
    outs:
      - data/processed/chunks.json

  vectorize:
    cmd: python vectorize_data.py
    deps:
      - vectorize_data.py
      - data/processed/chunks.json
      - params.yaml
    params:
      - vectorization
    outs:
      - data/processed/vector_index
