# This file saves the model as output on DVC
stages:
  train:
    cmd: python train_model.py
    deps:
      - train_model.py
      - params.yaml
      - data/
    params:
      - train
      - model
    outs:
      - models/model.pkl
    metrics:
      - metrics.json:
          cache: false
