# Parameters for LegalAIze Project (Audit & Search)

ingestion:
  chunk_size: 4000
  chunk_overlap: 500
  raw_data_dir: "data"
  processed_data_dir: "data/processed"

vectorization:
  model_name: "all-MiniLM-L6-v2"
  collection_name: "legal_docs"
  qdrant_host: "localhost"
  qdrant_port: 6333
  vector_index_path: "data/processed/vector_index"

precompute:
  top_k: 3  # number of chunks per requirement in precompute_rag
  chunks_output: "data/processed/requirement_chunks.json"
