# Parameters for LegalAIze Project (Audit & Search)

ingestion:
  chunk_size: 4000
  chunk_overlap: 500
  raw_data_dir: "data"
  processed_data_dir: "data/processed"

vectorization:
  model_name: "all-MiniLM-L6-v2"
  collection_name: "legal_docs"
  qdrant_host: "localhost"
  qdrant_port: 6333
  vector_index_path: "data/processed/vector_index"

precompute:
  top_k: 3  # number of chunks per requirement in precompute_rag
  chunks_output: "data/processed/requirement_chunks.json"

evaluation:
  backend_url: "http://localhost:8000"  # FastAPI audit endpoint base URL
  random_seed: 42
  llm_model: "gpt-3.5-turbo"  # documented for reproducibility
  llm_temperature: 0.1
  mlflow_tracking_uri: # use the MLFLOW_TRACKING_URI from .env
  mlflow_experiment: "rag_evaluation"
  metrics_output: "metrics/rag_eval.json"
  ground_truth:
    - name: "Evaluation1"
      document_path: "data/ground_truth/raw_data/Evaluation1/documentation.txt"
      report_path: "data/ground_truth/raw_data/Evaluation1/report.CSV"
    - name: "Evaluation2"
      document_path: "data/ground_truth/raw_data/Evaluation2/documentation.txt"
      report_path: "data/ground_truth/raw_data/Evaluation2/report.CSV"
